# Generated by Django 5.2.1 on 2025-05-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_subject_created_at_subject_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrequest',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='subject',
            field=models.ManyToManyField(to='main_app.subject'),
        ),
    ]
