# Generated by Django 5.2.1 on 2025-05-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_submitted_at_studentrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
