# Generated by Django 5.2.1 on 2025-05-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_studentrequest_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrequest',
            old_name='done',
            new_name='first_payment',
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='second_payment',
            field=models.BooleanField(default=False),
        ),
    ]
