# Generated by Django 5.2.1 on 2025-05-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_done_studentrequest_first_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='univ_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
