# Generated by Django 5.2.1 on 2025-05-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_studentrequest_email_studentrequest_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
