# Generated by Django 5.2.1 on 2025-05-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_studentrequest_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='first_payment',
            field=models.BooleanField(default=False),
        ),
    ]
