# Generated by Django 5.2.1 on 2025-05-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_subject_first_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='first_payment',
        ),
        migrations.AddField(
            model_name='subject',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
