# Generated by Django 5.2.1 on 2025-06-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_category_subject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='state',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10),
        ),
    ]
