# Generated by Django 5.2.1 on 2025-06-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_subject_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.TextField(),
        ),
    ]
