# Generated by Django 5.2.1 on 2025-06-04 06:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
