# Generated by Django 5.2.1 on 2025-06-04 06:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='attachment',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
