# Generated by Django 5.2.1 on 2025-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_studentrequest_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='advance_payment',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
